<template><div><h2 id="python与高程数据" tabindex="-1"><a class="header-anchor" href="#python与高程数据" aria-hidden="true">#</a> Python与高程数据</h2>
<h3 id="ascii-网格文件" tabindex="-1"><a class="header-anchor" href="#ascii-网格文件" aria-hidden="true">#</a> ASCII 网格文件</h3>
<h4 id="读取grids" tabindex="-1"><a class="header-anchor" href="#读取grids" aria-hidden="true">#</a> 读取grids</h4>
<ul>
<li>
<p>头部六行数据说明</p>
<ul>
<li>ncols 描述网格包含的列数，同时也代表x轴</li>
<li>yrows 描述网格包含的行数，同时也代表y轴</li>
<li>xllcorner 左下角x坐标，以m为单位的x轴最小值</li>
<li>yllcorner 左下角y坐标，y轴最小值</li>
<li>cellsize 描述单元格的尺寸或者栅格的分辨率</li>
<li>NODATA_value 为那些未被赋值的单元格提供默认值，一般采用-9999之歌数值</li>
</ul>
</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">import</span> numpy <span class="token keyword">as</span> np
arr <span class="token operator">=</span> np<span class="token punctuation">.</span>loadtxt<span class="token punctuation">(</span><span class="token string">'data/myGrid.asc'</span><span class="token punctuation">,</span>skiprows<span class="token operator">=</span><span class="token number">6</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="写入grids" tabindex="-1"><a class="header-anchor" href="#写入grids" aria-hidden="true">#</a> 写入grids</h4>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">import</span> numpy <span class="token keyword">as</span> np
arr <span class="token operator">=</span> np<span class="token punctuation">.</span>loadtxt<span class="token punctuation">(</span><span class="token string">'data/myGrid.asc'</span><span class="token punctuation">,</span>skiprows<span class="token operator">=</span><span class="token number">6</span><span class="token punctuation">)</span>
header <span class="token operator">=</span> <span class="token string">'ncols      {}\n'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
header <span class="token operator">+=</span><span class="token string">'nrows   {}'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
header <span class="token operator">+=</span><span class="token string">'xllcorner   277750.0\n'</span>
header <span class="token operator">+=</span><span class="token string">'yllcorner   6122250.0\n'</span>
header <span class="token operator">+=</span><span class="token string">'cellsize      1.0\n'</span>
header <span class="token operator">+=</span><span class="token string">'NODATA_value     -9999'</span>
np<span class="token punctuation">.</span>savetxt<span class="token punctuation">(</span><span class="token string">'data/selfGrid.asc'</span><span class="token punctuation">,</span>arr<span class="token punctuation">,</span>header<span class="token operator">=</span>header<span class="token punctuation">,</span>fmt<span class="token operator">=</span><span class="token string">'%1.2f'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="创建地形阴影" tabindex="-1"><a class="header-anchor" href="#创建地形阴影" aria-hidden="true">#</a> 创建地形阴影</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> linecache <span class="token keyword">import</span> getline
<span class="token keyword">import</span> numpy <span class="token keyword">as</span> np
<span class="token keyword">import</span> math

<span class="token comment"># 高程数据文件</span>
source <span class="token operator">=</span> <span class="token string">'data/dem/dem.asc'</span>
<span class="token comment"># 坡度格文件</span>
slopegrid<span class="token operator">=</span> <span class="token string">'data/dem/slope.asc'</span>
<span class="token comment"># 坡向网格文件</span>
aspectgrid<span class="token operator">=</span> <span class="token string">'data/dem/aspect.asc'</span>
<span class="token comment"># 输出渲染文件</span>
shadegrid <span class="token operator">=</span> <span class="token string">'data/dem/relief.asc'</span>

<span class="token comment"># 高程阴影参数</span>
<span class="token comment"># 日光方位</span>
azimuth <span class="token operator">=</span> <span class="token number">315.0</span>
<span class="token comment">#日光角度</span>
altitude <span class="token operator">=</span> <span class="token number">45.0</span>
<span class="token comment"># 高程放大比例</span>
z <span class="token operator">=</span> <span class="token number">1.0</span>
<span class="token comment"># 分辨率</span>
scale <span class="token operator">=</span> <span class="token number">1.0</span>
<span class="token comment"># NODATA</span>
NODATA <span class="token operator">=</span> <span class="token operator">-</span><span class="token number">9999</span>

<span class="token comment"># numpy库必需转换的操作</span>
deg2rad <span class="token operator">=</span> math<span class="token punctuation">.</span>pi <span class="token operator">/</span> <span class="token number">180.0</span>
rad2deg <span class="token operator">=</span> <span class="token number">180.0</span><span class="token operator">/</span>math<span class="token punctuation">.</span>pi

<span class="token comment"># 使用内置的linecache模块解析头部信息</span>
hdr <span class="token operator">=</span><span class="token punctuation">[</span>getline<span class="token punctuation">(</span>source<span class="token punctuation">,</span>i<span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">7</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
values <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token builtin">float</span><span class="token punctuation">(</span>h<span class="token punctuation">.</span>split<span class="token punctuation">(</span><span class="token string">" "</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">.</span>strip<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">for</span> h <span class="token keyword">in</span> hdr<span class="token punctuation">]</span>
cols<span class="token punctuation">,</span>rows<span class="token punctuation">,</span>lx<span class="token punctuation">,</span>ly<span class="token punctuation">,</span>cell<span class="token punctuation">,</span>nd <span class="token operator">=</span> values
xres <span class="token operator">=</span> cell
yres <span class="token operator">=</span> cell<span class="token operator">*</span> <span class="token operator">-</span><span class="token number">1</span>

<span class="token comment"># 加载dem数据</span>
arr <span class="token operator">=</span> np<span class="token punctuation">.</span>loadtxt<span class="token punctuation">(</span>source<span class="token punctuation">,</span>skiprows<span class="token operator">=</span><span class="token number">6</span><span class="token punctuation">)</span>

<span class="token comment"># 排除围绕边框之外2个像素的NODATA数据</span>
<span class="token comment"># 同时设立 3x3的窗口进行坡度计算</span>
window <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token keyword">for</span> row <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">for</span> col <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        window<span class="token punctuation">.</span>append<span class="token punctuation">(</span>arr<span class="token punctuation">[</span>row<span class="token punctuation">:</span> <span class="token punctuation">(</span>row <span class="token operator">+</span> arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">-</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span> col<span class="token punctuation">:</span> <span class="token punctuation">(</span>col <span class="token operator">+</span> arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token operator">-</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token comment"># 处理水平和竖直方向上的每个3x3窗体</span>
x <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">(</span>z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">6</span><span class="token punctuation">]</span> <span class="token punctuation">)</span> <span class="token operator">-</span> 
    <span class="token punctuation">(</span>z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">5</span><span class="token punctuation">]</span> <span class="token operator">+</span> z<span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">5</span><span class="token punctuation">]</span> <span class="token operator">+</span>z<span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">8</span><span class="token punctuation">]</span> <span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token punctuation">(</span><span class="token number">8.0</span> <span class="token operator">*</span> xres <span class="token operator">*</span> scale<span class="token punctuation">)</span>

y <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">(</span>z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">6</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">7</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">7</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">8</span><span class="token punctuation">]</span> <span class="token punctuation">)</span> <span class="token operator">-</span> 
    <span class="token punctuation">(</span>z <span class="token operator">*</span> window<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">+</span> z <span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token operator">+</span> z<span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token operator">+</span>z<span class="token operator">*</span>window<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span> <span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token punctuation">(</span><span class="token number">8.0</span> <span class="token operator">*</span> yres <span class="token operator">*</span> scale<span class="token punctuation">)</span>

<span class="token comment"># 计算坡度</span>
slope <span class="token operator">=</span> <span class="token number">90.0</span> <span class="token operator">-</span> np<span class="token punctuation">.</span>arctan<span class="token punctuation">(</span>np<span class="token punctuation">.</span>sqrt<span class="token punctuation">(</span>x <span class="token operator">*</span> x <span class="token operator">+</span> y <span class="token operator">*</span> y<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">*</span> rad2deg
<span class="token comment"># 计算坡向</span>
aspect <span class="token operator">=</span> np<span class="token punctuation">.</span>arctan2<span class="token punctuation">(</span>x<span class="token punctuation">,</span> y<span class="token punctuation">)</span>

<span class="token comment"># 计算晕渲阴影</span>
shaded <span class="token operator">=</span> np<span class="token punctuation">.</span>sin<span class="token punctuation">(</span>altitude <span class="token operator">*</span> deg2rad  <span class="token punctuation">)</span> <span class="token operator">*</span> np<span class="token punctuation">.</span>sin<span class="token punctuation">(</span>slope <span class="token operator">*</span> deg2rad<span class="token punctuation">)</span> <span class="token operator">+</span> np<span class="token punctuation">.</span>cos<span class="token punctuation">(</span>altitude <span class="token operator">*</span> deg2rad<span class="token punctuation">)</span> <span class="token operator">*</span> np<span class="token punctuation">.</span>cos<span class="token punctuation">(</span>slope<span class="token operator">*</span>
                                                                                                      deg2rad<span class="token punctuation">)</span> <span class="token operator">*</span> np<span class="token punctuation">.</span>cos<span class="token punctuation">(</span><span class="token punctuation">(</span>azimuth <span class="token operator">-</span> <span class="token number">90.0</span><span class="token punctuation">)</span> <span class="token operator">*</span> deg2rad <span class="token operator">-</span>aspect<span class="token punctuation">)</span>
<span class="token comment"># 阴影放大比例,0-1到0-255</span>
shaded <span class="token operator">=</span> shaded<span class="token operator">*</span><span class="token number">255</span>
<span class="token comment"># 生成新的头部</span>
header <span class="token operator">=</span> <span class="token string">'ncols      {}\n'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>shaded<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
header <span class="token operator">+=</span><span class="token string">'nrows   {}'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>shaded<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
header <span class="token operator">+=</span><span class="token string">'xllcorner   {}\n'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>lx <span class="token operator">+</span> <span class="token punctuation">(</span>cell <span class="token operator">*</span><span class="token punctuation">(</span>cols <span class="token operator">-</span> shaded<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
header <span class="token operator">+=</span><span class="token string">'yllcorner   {}\n'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>ly <span class="token operator">+</span> <span class="token punctuation">(</span>cell <span class="token operator">*</span> <span class="token punctuation">(</span>rows <span class="token operator">-</span> shaded<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
header <span class="token operator">+=</span><span class="token string">'cellsize      {}\n'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>cell<span class="token punctuation">)</span>
header <span class="token operator">+=</span><span class="token string">'NODATA_value     {}\n'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>NODATA<span class="token punctuation">)</span>

<span class="token comment"># 为窗体设定NODATA值</span>
<span class="token keyword">for</span> pane <span class="token keyword">in</span> window<span class="token punctuation">:</span>
    slope<span class="token punctuation">[</span>pane <span class="token operator">==</span> nd<span class="token punctuation">]</span> <span class="token operator">=</span> NODATA
    aspect<span class="token punctuation">[</span>pane <span class="token operator">==</span> nd<span class="token punctuation">]</span> <span class="token operator">=</span> NODATA
    shaded<span class="token punctuation">[</span>pane <span class="token operator">==</span> nd<span class="token punctuation">]</span> <span class="token operator">=</span> NODATA

    
<span class="token comment"># 打开输出文件添加头部信息保存数据</span>
<span class="token keyword">with</span> <span class="token builtin">open</span><span class="token punctuation">(</span>slopegrid<span class="token punctuation">,</span><span class="token string">'wb'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> f<span class="token punctuation">:</span>
    f<span class="token punctuation">.</span>write<span class="token punctuation">(</span><span class="token builtin">bytes</span><span class="token punctuation">(</span>header<span class="token punctuation">,</span><span class="token string">'UTF-8'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    np<span class="token punctuation">.</span>savetxt<span class="token punctuation">(</span>f<span class="token punctuation">,</span>slope<span class="token punctuation">,</span>fmt<span class="token operator">=</span><span class="token string">'%4i'</span><span class="token punctuation">)</span>

<span class="token keyword">with</span> <span class="token builtin">open</span><span class="token punctuation">(</span>aspectgrid<span class="token punctuation">,</span><span class="token string">'wb'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> f<span class="token punctuation">:</span>
    f<span class="token punctuation">.</span>write<span class="token punctuation">(</span><span class="token builtin">bytes</span><span class="token punctuation">(</span>header<span class="token punctuation">,</span><span class="token string">'UTF-8'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    np<span class="token punctuation">.</span>savetxt<span class="token punctuation">(</span>f<span class="token punctuation">,</span>aspect<span class="token punctuation">,</span>fmt<span class="token operator">=</span><span class="token string">'%4i'</span><span class="token punctuation">)</span>

<span class="token keyword">with</span> <span class="token builtin">open</span><span class="token punctuation">(</span>shadegrid<span class="token punctuation">,</span><span class="token string">'wb'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> f<span class="token punctuation">:</span>
     f<span class="token punctuation">.</span>write<span class="token punctuation">(</span><span class="token builtin">bytes</span><span class="token punctuation">(</span>header<span class="token punctuation">,</span><span class="token string">'UTF-8'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
     np<span class="token punctuation">.</span>savetxt<span class="token punctuation">(</span>f<span class="token punctuation">,</span>shaded<span class="token punctuation">,</span>fmt<span class="token operator">=</span><span class="token string">'%4i'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


