<template><div><h2 id="gdal数据模型" tabindex="-1"><a class="header-anchor" href="#gdal数据模型" aria-hidden="true">#</a> GDAL数据模型</h2>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>    1、重要三概念：数据集、栅格波段、颜色表。
    2、一个数据集是相关的栅格波段和一些相关的信息的集合。负责所有波段的地理参考定义和坐标定义。
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="数据集放射地理转换" tabindex="-1"><a class="header-anchor" href="#数据集放射地理转换" aria-hidden="true">#</a> 数据集放射地理转换</h3>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>    常用放射变换表示栅格位置和地理参考坐标之间的关系。放射变换包含留个参数。
    GDALDateset.GetGeoTransform()返回。
    Xgeo = GT(0) + Xpixel*GT(1) + Yline*GT(2)
    Ygeo = GT(3) + Xpixel*GT(4) + Yline*GT(5)
    
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="gdal读取栅格的基本信息" tabindex="-1"><a class="header-anchor" href="#gdal读取栅格的基本信息" aria-hidden="true">#</a> GDAL读取栅格的基本信息</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token triple-quoted-string string">'''
gt[0] 栅格左上角横坐标
gt[3] 栅格左上角纵坐标
gt[2],gt[4] 对应上北下南，没有发生旋转值为0
gt[1] 栅格水平空间分辨率
gt[5] 栅格垂直空间分辨率
通常情况下gt[1]和gt[5]相等

'''</span>
<span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal

ds <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Open<span class="token punctuation">(</span><span class="token string">'learn.tif'</span><span class="token punctuation">)</span>

<span class="token comment"># 输出栅格的描述信息</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>ds<span class="token punctuation">.</span>GetDescription<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token comment"># 获取栅格数据集的波段数</span>
raster_count <span class="token operator">=</span> ds<span class="token punctuation">.</span>RasterCount
<span class="token keyword">print</span><span class="token punctuation">(</span>raster_count<span class="token punctuation">)</span>
<span class="token comment"># 获取提一个波段</span>
band <span class="token operator">=</span> ds<span class="token punctuation">.</span>GetRasterBand<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span>
<span class="token comment"># 波段类型</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>band<span class="token punctuation">.</span>DataType<span class="token punctuation">)</span>
<span class="token comment"># 波段大小</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>band<span class="token punctuation">.</span>XSize<span class="token punctuation">,</span>band<span class="token punctuation">.</span>YSize<span class="token punctuation">)</span>
<span class="token comment"># 波段数据的属性</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>band<span class="token punctuation">.</span>GetNoDataValue<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token comment"># Maximum 是表示在本波段数值中最大的值,Minimum就是表示本波段中最小的值</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>band<span class="token punctuation">.</span>GetMaximum<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>band<span class="token punctuation">.</span>GetMinimum<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token comment">#</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>band<span class="token punctuation">.</span>ComputeRasterMinMax<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token comment"># 栅格数据的宽度</span>
x_size <span class="token operator">=</span> ds<span class="token punctuation">.</span>RasterXSize
<span class="token comment"># 栅格数据的高度</span>
y_size <span class="token operator">=</span> ds<span class="token punctuation">.</span>RasterYSize
<span class="token keyword">print</span><span class="token punctuation">(</span>x_size<span class="token punctuation">,</span>y_size<span class="token punctuation">)</span>
<span class="token comment"># 获取栅格的6个参数</span>
gt  <span class="token operator">=</span> ds<span class="token punctuation">.</span>GetGeoTransform<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token comment"># 左上角</span>
ul_x <span class="token operator">=</span> gt<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span>
ul_y <span class="token operator">=</span> gt<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span>
<span class="token comment"># 右下角</span>
lr_x  <span class="token operator">=</span> gt<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">+</span> x_size<span class="token operator">*</span>gt<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token operator">+</span> y_size<span class="token operator">*</span>gt<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span>
lr_y <span class="token operator">=</span> gt<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span> <span class="token operator">+</span> x_size<span class="token operator">*</span>gt<span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">]</span> <span class="token operator">+</span> y_size<span class="token operator">*</span>gt<span class="token punctuation">[</span><span class="token number">5</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>ul_x<span class="token punctuation">,</span>ul_y<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>lr_x<span class="token punctuation">,</span>lr_y<span class="token punctuation">)</span>
<span class="token comment"># 栅格数据的投影</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>ds<span class="token punctuation">.</span>GetProjection<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token comment"># 读取栅格元数据</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>ds<span class="token punctuation">.</span>GetMetadata<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token comment">#</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>gt<span class="token punctuation">)</span>

<span class="token comment"># print out (114.11064773797989, 2.682209014892578e-06, 0.0, 22.29586511850357, 0.0, -2.682209014892578e-06)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="gdal-创建栅格影像" tabindex="-1"><a class="header-anchor" href="#gdal-创建栅格影像" aria-hidden="true">#</a> GDAL 创建栅格影像</h3>
<ul>
<li>创建单波段影像</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal<span class="token punctuation">,</span>osr
<span class="token keyword">import</span> numpy <span class="token keyword">as</span> np
<span class="token comment"># 设置驱动</span>
driver <span class="token operator">=</span> gdal<span class="token punctuation">.</span>GetDriverByName<span class="token punctuation">(</span><span class="token string">'GTiff'</span><span class="token punctuation">)</span>
filename <span class="token operator">=</span> <span class="token string">'ddd.tif'</span>
w<span class="token punctuation">,</span>h <span class="token operator">=</span><span class="token number">255</span><span class="token punctuation">,</span><span class="token number">255</span>
<span class="token comment"># 波段个数</span>
bands<span class="token operator">=</span><span class="token number">1</span>
<span class="token comment"># 数据类型</span>
t <span class="token operator">=</span> gdal<span class="token punctuation">.</span>GDT_Byte
<span class="token comment"># 创建tif数据</span>
ds <span class="token operator">=</span> driver<span class="token punctuation">.</span>Create<span class="token punctuation">(</span>filename<span class="token punctuation">,</span>w<span class="token punctuation">,</span>h<span class="token punctuation">,</span>bands<span class="token punctuation">,</span>t<span class="token punctuation">)</span>
<span class="token comment"># 设置栅格六参数,这里随便设置而已</span>
ds<span class="token punctuation">.</span>SetGeoTransform<span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">153312</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">451343</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token comment"># 空间参考</span>
srs <span class="token operator">=</span> osr<span class="token punctuation">.</span>SpatialReference<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token comment"># 生成具有给定 UTM 区域的全套横向墨卡托投影参数的投影定义</span>
srs<span class="token punctuation">.</span>SetUTM<span class="token punctuation">(</span><span class="token number">11</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">)</span>
<span class="token comment"># 设置 GeogCS</span>
srs<span class="token punctuation">.</span>SetWellKnownGeogCS<span class="token punctuation">(</span><span class="token string">'WGS84'</span><span class="token punctuation">)</span>
<span class="token comment"># 设置栅格投影</span>
ds<span class="token punctuation">.</span>SetProjection<span class="token punctuation">(</span>srs<span class="token punctuation">.</span>ExportToWkt<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token comment"># 生成raster数据</span>
raster <span class="token operator">=</span> np<span class="token punctuation">.</span>ones<span class="token punctuation">(</span><span class="token punctuation">(</span>w<span class="token punctuation">,</span>h<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">138</span>
ds<span class="token punctuation">.</span>GetRasterBand<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span>WriteArray<span class="token punctuation">(</span>raster<span class="token punctuation">)</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Pillow与GDAL读取数据的转换</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal<span class="token punctuation">,</span>osr
<span class="token keyword">import</span> numpy <span class="token keyword">as</span> np
<span class="token keyword">from</span> PIL <span class="token keyword">import</span> Image

ds <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Open<span class="token punctuation">(</span><span class="token string">'demo.tif'</span><span class="token punctuation">)</span>
data <span class="token operator">=</span> ds<span class="token punctuation">.</span>ReadRaster<span class="token punctuation">(</span><span class="token number">30</span><span class="token punctuation">,</span><span class="token number">70</span><span class="token punctuation">,</span><span class="token number">5</span><span class="token punctuation">,</span><span class="token number">5</span><span class="token punctuation">)</span>


im <span class="token operator">=</span> Image<span class="token punctuation">.</span><span class="token builtin">open</span><span class="token punctuation">(</span><span class="token string">"demo.tif"</span><span class="token punctuation">)</span>
region <span class="token operator">=</span> im<span class="token punctuation">.</span>crop<span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token number">30</span><span class="token punctuation">,</span><span class="token number">70</span><span class="token punctuation">,</span><span class="token number">5</span><span class="token punctuation">,</span><span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>region<span class="token punctuation">.</span>tobytes<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>

<span class="token comment"># 转成PIL格式</span>
datas <span class="token operator">=</span> <span class="token punctuation">[</span>i <span class="token keyword">for</span> i <span class="token keyword">in</span> data<span class="token punctuation">]</span>
datas <span class="token operator">=</span> <span class="token punctuation">[</span>np<span class="token punctuation">.</span>reshape<span class="token punctuation">(</span>i<span class="token punctuation">,</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> data<span class="token punctuation">]</span>
datas <span class="token operator">=</span> np<span class="token punctuation">.</span>concatenate<span class="token punctuation">(</span>datas<span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>datas<span class="token punctuation">.</span>tostring<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="常用gdal-指令" tabindex="-1"><a class="header-anchor" href="#常用gdal-指令" aria-hidden="true">#</a> 常用GDAL 指令</h2>
<h3 id="gdalwrap-截取gtiff" tabindex="-1"><a class="header-anchor" href="#gdalwrap-截取gtiff" aria-hidden="true">#</a> gdalwrap 截取GTiff</h3>
<ul>
<li>shell</li>
</ul>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>gdalwarp <span class="token parameter variable">-t_srs</span> EPSG:4326 <span class="token parameter variable">-te</span> <span class="token number">114.14943</span> <span class="token number">22.30447</span> <span class="token number">114.15556</span> <span class="token number">22.31311</span> <span class="token parameter variable">-of</span> JPEG demo.tif out.png
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><ul>
<li>python</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    <span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token keyword">import</span> gdal
<span class="token keyword">import</span> os

<span class="token keyword">def</span> <span class="token function">wrapTiff</span><span class="token punctuation">(</span>source<span class="token punctuation">,</span> dest_tif<span class="token punctuation">,</span> dest_img<span class="token punctuation">,</span> outputBounds<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token comment"># gdalwarp -t_srs EPSG:4326 -te 114.14943 22.30447 114.15556 22.31311 -of JPEG 油尖旺区_卫图_20181004_Level_19.tif out.png</span>
    <span class="token keyword">try</span><span class="token punctuation">:</span>
        dirName<span class="token punctuation">,</span> filename <span class="token operator">=</span> os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>split<span class="token punctuation">(</span>dest_tif<span class="token punctuation">)</span>
        <span class="token keyword">if</span> <span class="token keyword">not</span> os<span class="token punctuation">.</span>path<span class="token punctuation">.</span>exists<span class="token punctuation">(</span>dirName<span class="token punctuation">)</span><span class="token punctuation">:</span>
            os<span class="token punctuation">.</span>makedirs<span class="token punctuation">(</span>dirName<span class="token punctuation">)</span>
        opt <span class="token operator">=</span> gdal<span class="token punctuation">.</span>WarpOptions<span class="token punctuation">(</span>outputBounds<span class="token operator">=</span>outputBounds<span class="token punctuation">,</span> <span class="token builtin">format</span><span class="token operator">=</span><span class="token string">'MEM'</span><span class="token punctuation">,</span> dstSRS<span class="token operator">=</span><span class="token string">"EPSG:4326"</span><span class="token punctuation">)</span>
        ds <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Warp<span class="token punctuation">(</span>dest_tif<span class="token punctuation">,</span> source<span class="token punctuation">,</span> options<span class="token operator">=</span>opt<span class="token punctuation">)</span>
        driver <span class="token operator">=</span> gdal<span class="token punctuation">.</span>GetDriverByName<span class="token punctuation">(</span><span class="token string">"GTiff"</span><span class="token punctuation">)</span>
        driver<span class="token punctuation">.</span>CreateCopy<span class="token punctuation">(</span>dest_tif<span class="token punctuation">,</span> ds<span class="token punctuation">)</span>

        ds <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Warp<span class="token punctuation">(</span>dest_img<span class="token punctuation">,</span> source<span class="token punctuation">,</span> options<span class="token operator">=</span>opt<span class="token punctuation">)</span>
        driver <span class="token operator">=</span> gdal<span class="token punctuation">.</span>GetDriverByName<span class="token punctuation">(</span><span class="token string">"JPEG"</span><span class="token punctuation">)</span>
        driver<span class="token punctuation">.</span>CreateCopy<span class="token punctuation">(</span>dest_img<span class="token punctuation">,</span> ds<span class="token punctuation">)</span>
        <span class="token keyword">return</span> <span class="token boolean">True</span>
    <span class="token keyword">except</span> Exception <span class="token keyword">as</span> e<span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span>
        <span class="token keyword">return</span> <span class="token boolean">False</span>   
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="gdal2tiles-gtiff文件转成raster瓦片指令" tabindex="-1"><a class="header-anchor" href="#gdal2tiles-gtiff文件转成raster瓦片指令" aria-hidden="true">#</a> gdal2tiles GTiff文件转成raster瓦片指令 <br /></h3>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>gdal2tiles.py <span class="token parameter variable">--xyz</span>  <span class="token parameter variable">-z</span> <span class="token number">1</span>-19  <span class="token parameter variable">-p</span> mercator <span class="token parameter variable">-w</span> all <span class="token parameter variable">-r</span> average <span class="token parameter variable">-s</span> EPSG:4326 <span class="token parameter variable">-a</span> <span class="token number">0.0</span> <span class="token parameter variable">--processes</span><span class="token operator">=</span><span class="token number">6</span> input.tif output_dir
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="gdal-translate" tabindex="-1"><a class="header-anchor" href="#gdal-translate" aria-hidden="true">#</a> gdal_translate  <br /></h3>
<ul>
<li>shell</li>
</ul>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># jpg、png 转成geo tiff</span>
gdal_translate <span class="token parameter variable">-of</span> GTiff <span class="token parameter variable">-a_srs</span> EPSG:4326 <span class="token parameter variable">-a_ullr</span>  ulx uly lrx lry  input.jpg  out.tif

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>python</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    <span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token keyword">import</span> gdal
<span class="token keyword">import</span> os
<span class="token keyword">def</span> <span class="token function">tiff2png</span><span class="token punctuation">(</span>source<span class="token punctuation">,</span> out<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">try</span><span class="token punctuation">:</span>
        ds <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Open<span class="token punctuation">(</span>source<span class="token punctuation">)</span>
        info <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Info<span class="token punctuation">(</span>ds<span class="token operator">=</span>ds<span class="token punctuation">,</span><span class="token builtin">format</span><span class="token operator">=</span><span class="token string">'json'</span><span class="token punctuation">)</span>
        center <span class="token operator">=</span> info<span class="token punctuation">[</span><span class="token string">'cornerCoordinates'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'center'</span><span class="token punctuation">]</span>
        opt <span class="token operator">=</span> gdal<span class="token punctuation">.</span>TranslateOptions<span class="token punctuation">(</span><span class="token builtin">format</span><span class="token operator">=</span><span class="token string">'PNG'</span><span class="token punctuation">,</span> height<span class="token operator">=</span><span class="token number">1024</span><span class="token punctuation">,</span> width<span class="token operator">=</span><span class="token number">1024</span><span class="token punctuation">)</span>
        gdal<span class="token punctuation">.</span>Translate<span class="token punctuation">(</span>out<span class="token punctuation">,</span> source<span class="token punctuation">,</span> options<span class="token operator">=</span>opt<span class="token punctuation">)</span>
        center_str <span class="token operator">=</span> <span class="token builtin">str</span><span class="token punctuation">(</span>center<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">+</span><span class="token string">","</span><span class="token operator">+</span><span class="token builtin">str</span><span class="token punctuation">(</span>center<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
        <span class="token keyword">return</span> center_str
    <span class="token keyword">except</span> Exception <span class="token keyword">as</span> e<span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span>
        <span class="token keyword">return</span> <span class="token boolean">None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="图像波段切换" tabindex="-1"><a class="header-anchor" href="#图像波段切换" aria-hidden="true">#</a> 图像波段切换</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 图像波段变换</span>
<span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal_array
src <span class="token operator">=</span> <span class="token string">'data/FalseColor.tif'</span>
arr <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>LoadFile<span class="token punctuation">(</span>src<span class="token punctuation">)</span>
output <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>SaveArray<span class="token punctuation">(</span>arr<span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">:</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token string">'data/swap.tif'</span><span class="token punctuation">,</span><span class="token builtin">format</span><span class="token operator">=</span><span class="token string">'GTiff'</span><span class="token punctuation">,</span>prototype<span class="token operator">=</span>src<span class="token punctuation">)</span>
output<span class="token operator">=</span><span class="token boolean">None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="图像分类" tabindex="-1"><a class="header-anchor" href="#图像分类" aria-hidden="true">#</a> 图像分类</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 图像分类</span>
<span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal_array
src <span class="token operator">=</span> <span class="token string">'data/thermal/thermal.tif'</span>
tgt <span class="token operator">=</span> <span class="token string">'data/thermal/classified.jpg'</span>

src_arr <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>LoadFile<span class="token punctuation">(</span>src<span class="token punctuation">)</span>
<span class="token comment"># 根据类别数目把直方图分割成20个颜色区间</span>
classes <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>histogram<span class="token punctuation">(</span>src_arr<span class="token punctuation">,</span>bins<span class="token operator">=</span><span class="token number">20</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span>
<span class="token comment"># 颜色查找表的记录必须为len(classes) +1</span>
<span class="token comment"># R G B元组</span>
lut <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">191</span><span class="token punctuation">,</span> <span class="token number">48</span><span class="token punctuation">,</span> <span class="token number">48</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">166</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">155</span><span class="token punctuation">,</span> <span class="token number">155</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
       <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">116</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">191</span><span class="token punctuation">,</span> <span class="token number">113</span><span class="token punctuation">,</span> <span class="token number">48</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">178</span><span class="token punctuation">,</span> <span class="token number">115</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">153</span><span class="token punctuation">,</span> <span class="token number">153</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">29</span><span class="token punctuation">,</span> <span class="token number">115</span><span class="token punctuation">,</span> <span class="token number">155</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
       <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">99</span><span class="token punctuation">,</span> <span class="token number">99</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">166</span><span class="token punctuation">,</span> <span class="token number">75</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">204</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">51</span><span class="token punctuation">,</span> <span class="token number">204</span><span class="token punctuation">,</span> <span class="token number">204</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">150</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
       <span class="token punctuation">[</span><span class="token number">92</span><span class="token punctuation">,</span> <span class="token number">204</span><span class="token punctuation">,</span> <span class="token number">204</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">38</span><span class="token punctuation">,</span> <span class="token number">153</span><span class="token punctuation">,</span> <span class="token number">38</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">133</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">57</span><span class="token punctuation">,</span> <span class="token number">230</span><span class="token punctuation">,</span> <span class="token number">57</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">103</span><span class="token punctuation">,</span> <span class="token number">230</span><span class="token punctuation">,</span> <span class="token number">103</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
       <span class="token punctuation">[</span><span class="token number">184</span><span class="token punctuation">,</span> <span class="token number">138</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">]</span>
<span class="token comment"># 分割初始值</span>
start <span class="token operator">=</span> <span class="token number">1</span>
p <span class="token operator">=</span> <span class="token number">0</span>
<span class="token comment"># 创建一个RGB颜色的JPEG输出图片</span>
rgb <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>zeros<span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">,</span>src_arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span>src_arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">)</span><span class="token punctuation">,</span>gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>float32<span class="token punctuation">)</span>
<span class="token comment"># 处理所有类并声明颜色</span>
<span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>classes<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token comment"># 获取标记的信息</span>
    mask <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>logical_and<span class="token punctuation">(</span>start <span class="token operator">&lt;=</span>src_arr<span class="token punctuation">,</span>src_arr<span class="token operator">&lt;=</span>classes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span>
    <span class="token keyword">for</span> j <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>lut<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 选择标记数据</span>
        rgb<span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token operator">=</span>gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>choose<span class="token punctuation">(</span>mask<span class="token punctuation">,</span> <span class="token punctuation">(</span>rgb<span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">,</span>lut<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        p <span class="token operator">=</span>p<span class="token operator">+</span><span class="token number">1</span>
    start <span class="token operator">=</span> classes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token operator">+</span><span class="token number">1</span>
output <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>SaveArray<span class="token punctuation">(</span>rgb<span class="token punctuation">.</span>astype<span class="token punctuation">(</span>gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>uint8<span class="token punctuation">)</span><span class="token punctuation">,</span>tgt<span class="token punctuation">,</span><span class="token builtin">format</span><span class="token operator">=</span><span class="token string">'JPEG'</span><span class="token punctuation">)</span>
output <span class="token operator">=</span> <span class="token boolean">None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="特征提取" tabindex="-1"><a class="header-anchor" href="#特征提取" aria-hidden="true">#</a> 特征提取</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 图像特征提取</span>
<span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal_array
src <span class="token operator">=</span> <span class="token string">'data/islands/islands.tif'</span>
tgt <span class="token operator">=</span> <span class="token string">'data/islands/islands_classified.tif'</span>
<span class="token comment"># 加载tif</span>
src_arr <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>LoadFile<span class="token punctuation">(</span>src<span class="token punctuation">)</span>
<span class="token comment"># 根据类别数目把直方图分割成20个颜色区间</span>
classes <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>histogram<span class="token punctuation">(</span>src_arr<span class="token punctuation">,</span>bins<span class="token operator">=</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span>
lut <span class="token operator">=</span> <span class="token punctuation">[</span> <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">255</span><span class="token punctuation">]</span> <span class="token punctuation">]</span>
<span class="token comment"># 分类起始</span>
start <span class="token operator">=</span> <span class="token number">1</span>
<span class="token comment"># 建立输出图片</span>
rgb <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>zeros<span class="token punctuation">(</span> <span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">,</span> src_arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> src_arr<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>float32<span class="token punctuation">)</span>

<span class="token comment"># 处理所有类别并分配颜色</span>
<span class="token keyword">for</span> i  <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>classes<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    mask <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>logical_and<span class="token punctuation">(</span>start<span class="token operator">&lt;=</span>src_arr<span class="token punctuation">,</span>  src_arr<span class="token operator">&lt;=</span>classes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span>
    <span class="token keyword">for</span> j <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>lut<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        rgb<span class="token punctuation">[</span>j<span class="token punctuation">]</span> <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>choose<span class="token punctuation">(</span>mask<span class="token punctuation">,</span> <span class="token punctuation">(</span>rgb<span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">,</span> lut<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">)</span>
    start <span class="token operator">=</span> classes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token operator">+</span><span class="token number">1</span>

output <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>SaveArray<span class="token punctuation">(</span>rgb<span class="token punctuation">.</span>astype<span class="token punctuation">(</span>gdal_array<span class="token punctuation">.</span>numpy<span class="token punctuation">.</span>uint8<span class="token punctuation">)</span><span class="token punctuation">,</span> tgt<span class="token punctuation">,</span> <span class="token builtin">format</span><span class="token operator">=</span><span class="token string">'GTiff'</span> <span class="token punctuation">)</span>
output <span class="token operator">=</span> <span class="token boolean">None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>特征提取出shapefile</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal<span class="token punctuation">,</span> ogr<span class="token punctuation">,</span> osr
 
<span class="token comment"># 阈值化后的输出栅格文件名称</span>
src <span class="token operator">=</span> <span class="token string">"data/islands/islands_classified.tif"</span>
<span class="token comment"># 输出的shapefile文件名称</span>
tgt <span class="token operator">=</span> <span class="token string">"data/islands/extract.shp"</span>
<span class="token comment"># 图层名称</span>
tgtLayer <span class="token operator">=</span> <span class="token string">"extract"</span>
<span class="token comment"># 打开输入的栅格文件</span>
srcDS <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Open<span class="token punctuation">(</span>src<span class="token punctuation">)</span>
<span class="token comment"># 获取第一个波段</span>
band <span class="token operator">=</span> srcDS<span class="token punctuation">.</span>GetRasterBand<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span>
<span class="token comment"># 让gdal库使用该波段作为遮罩层</span>
mask <span class="token operator">=</span> band
<span class="token comment"># 创建输出的shapefile文件</span>
driver <span class="token operator">=</span> ogr<span class="token punctuation">.</span>GetDriverByName<span class="token punctuation">(</span><span class="token string">"ESRI Shapefile"</span><span class="token punctuation">)</span>
shp <span class="token operator">=</span> driver<span class="token punctuation">.</span>CreateDataSource<span class="token punctuation">(</span>tgt<span class="token punctuation">)</span>
<span class="token comment"># 拷贝空间索引</span>
srs <span class="token operator">=</span> osr<span class="token punctuation">.</span>SpatialReference<span class="token punctuation">(</span><span class="token punctuation">)</span>
srs<span class="token punctuation">.</span>ImportFromWkt<span class="token punctuation">(</span>srcDS<span class="token punctuation">.</span>GetProjectionRef<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
layer <span class="token operator">=</span> shp<span class="token punctuation">.</span>CreateLayer<span class="token punctuation">(</span>tgtLayer<span class="token punctuation">,</span> srs<span class="token operator">=</span>srs<span class="token punctuation">)</span>
<span class="token comment"># 创建dbf文件</span>
fd <span class="token operator">=</span> ogr<span class="token punctuation">.</span>FieldDefn<span class="token punctuation">(</span><span class="token string">"DN"</span><span class="token punctuation">,</span> ogr<span class="token punctuation">.</span>OFTInteger<span class="token punctuation">)</span>
layer<span class="token punctuation">.</span>CreateField<span class="token punctuation">(</span>fd<span class="token punctuation">)</span>
dst_field <span class="token operator">=</span> <span class="token number">0</span>
<span class="token comment"># 从图片中自动提取特征</span>
extract <span class="token operator">=</span> gdal<span class="token punctuation">.</span>Polygonize<span class="token punctuation">(</span>band<span class="token punctuation">,</span> mask<span class="token punctuation">,</span> layer<span class="token punctuation">,</span> dst_field<span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token boolean">None</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="变化检测" tabindex="-1"><a class="header-anchor" href="#变化检测" aria-hidden="true">#</a> 变化检测</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 变化检测</span>
<span class="token keyword">from</span> osgeo <span class="token keyword">import</span> gdal<span class="token punctuation">,</span> gdal_array
<span class="token keyword">import</span> numpy <span class="token keyword">as</span> np
 
<span class="token comment"># 飓风前影像</span>
img1 <span class="token operator">=</span> <span class="token string">"./data/before/before.tif"</span>
<span class="token comment"># 飓风后影像</span>
img2 <span class="token operator">=</span> <span class="token string">"./data/after/after.tif"</span>
 
<span class="token comment"># 将上述图像载入数组</span>
arr1 <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>LoadFile<span class="token punctuation">(</span>img1<span class="token punctuation">)</span><span class="token punctuation">.</span>astype<span class="token punctuation">(</span>np<span class="token punctuation">.</span>int8<span class="token punctuation">)</span>
arr2 <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>LoadFile<span class="token punctuation">(</span>img2<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">.</span>astype<span class="token punctuation">(</span>np<span class="token punctuation">.</span>int8<span class="token punctuation">)</span>
 
<span class="token comment"># 在图片数组上执行差值操作</span>
diff <span class="token operator">=</span> arr2 <span class="token operator">-</span> arr1
 
<span class="token comment"># 建立类别架构并将变化特征隔离</span>
classes <span class="token operator">=</span> np<span class="token punctuation">.</span>histogram<span class="token punctuation">(</span>diff<span class="token punctuation">,</span> bins<span class="token operator">=</span><span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span>
 
<span class="token comment"># 用黑色遮罩不是特变明显的变化特征</span>
lut <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
       <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">255</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">]</span>
<span class="token comment"># 类别初始值</span>
start <span class="token operator">=</span> <span class="token number">1</span>
<span class="token comment"># 创建输出图片</span>
rgb <span class="token operator">=</span> np<span class="token punctuation">.</span>zeros<span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">,</span> diff<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> diff<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">)</span><span class="token punctuation">,</span> np<span class="token punctuation">.</span>int8<span class="token punctuation">)</span>
 
<span class="token comment"># 处理所有类别并配色</span>
<span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>classes<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    mask <span class="token operator">=</span> np<span class="token punctuation">.</span>logical_and<span class="token punctuation">(</span>start <span class="token operator">&lt;=</span> diff<span class="token punctuation">,</span> diff <span class="token operator">&lt;=</span> classes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span>
    <span class="token keyword">for</span> j <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>lut<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        rgb<span class="token punctuation">[</span>j<span class="token punctuation">]</span> <span class="token operator">=</span> np<span class="token punctuation">.</span>choose<span class="token punctuation">(</span>mask<span class="token punctuation">,</span> <span class="token punctuation">(</span>rgb<span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">,</span> lut<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    start <span class="token operator">=</span> classes<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token number">1</span>
 
<span class="token comment"># 保存图片结果</span>
output <span class="token operator">=</span> gdal_array<span class="token punctuation">.</span>SaveArray<span class="token punctuation">(</span>rgb<span class="token punctuation">,</span> <span class="token string">"data/change.tif"</span><span class="token punctuation">,</span> <span class="token builtin">format</span><span class="token operator">=</span><span class="token string">"GTiff"</span><span class="token punctuation">,</span> prototype<span class="token operator">=</span>img2<span class="token punctuation">)</span>
output <span class="token operator">=</span> <span class="token boolean">None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


